AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: XTime appointment integration

Parameters:
  Environment:
    Description: The name of the runtime environment
    Type: String
    AllowedPattern: "^[a-zA-z0-9-]+$"
    ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens

Conditions:
  IsProd:
    Fn::Equals:
      - Ref: AWS::AccountId
      - 196800776222
  IsUsEast1: !Equals [!Ref "AWS::Region", "us-east-1"]

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
        ENVIRONMENT: !Ref Environment
        LOGLEVEL: INFO
        SNS_TOPIC_ARN: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AccessSecretsManager
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:UpdateSecret  # Add this line
                Resource:
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/appt-integration-partners*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/appt-integration-partners*",
                    ]
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/xtime_token*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/xtime_token*",
                    ]
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: SNSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource:
                - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'

  CreateAppointments:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub xtime-${Environment}-CreateAppointments
      CodeUri: app/
      Handler: appointment_handler.create_appointment
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn

  CreateAppointmentsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/xtime-${Environment}-CreateAppointments"

  CreateAppointmentsCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "xtime-${Environment}-CreateAppointmentsFailureAlarm"
      AlarmDescription: "Alarm for failed invocations of CreateAppointments Lambda"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: "FunctionName"
          Value: !Ref CreateAppointments
      Statistic: "Sum"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'

  GetAppTimeSlots:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub xtime-${Environment}-GetAppTimeSlots
      CodeUri: app/
      Handler: appointment_handler.get_appt_time_slots
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn

  GetAppTimeSlotsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/xtime-${Environment}-GetAppTimeSlots"

  GetAppTimeSlotsCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "xtime-${Environment}-GetAppTimeSlotsFailureAlarm"
      AlarmDescription: "Alarm for failed invocations of GetAppTimeSlots Lambda"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: "FunctionName"
          Value: !Ref GetAppTimeSlots
      Statistic: "Sum"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'

  GetAppointments:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub xtime-${Environment}-GetAppointments
      CodeUri: app/
      Handler: appointment_handler.get_appointments
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn

  GetAppointmentsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/xtime-${Environment}-GetAppointments"

  GetAppointmentsCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "xtime-${Environment}-GetAppointmentsFailureAlarm"
      AlarmDescription: "Alarm for failed invocations of GetAppointments Lambda"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: "FunctionName"
          Value: !Ref GetAppointments
      Statistic: "Sum"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
  
  GetDealerOpcodes:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub xtime-${Environment}-GetDealerOpcodes
      CodeUri: app/
      Handler: appointment_handler.get_dealer_codes
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn

  GetDealerOpcodesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/xtime-${Environment}-GetDealerOpcodes"

  UpdateAppointment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub xtime-${Environment}-UpdateAppointment
      CodeUri: app/
      Handler: appointment_handler.update_appointment
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn

  UpdateAppointmentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/xtime-${Environment}-UpdateAppointment"

  UpdateAppointmentCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "xtime-${Environment}-UpdateAppointmentFailureAlarm"
      AlarmDescription: "Alarm for failed invocations of UpdateAppointment Lambda"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: "FunctionName"
          Value: !Ref UpdateAppointment
      Statistic: "Sum"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
