AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: dealerpeak crm integration

Parameters:
  Environment:
    Description: The name of the runtime environment
    Type: String
    AllowedPattern: "^[a-zA-z0-9-]+$"
    ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens
  CEAlertTopicArn:
    Description: The ARN of the SNS topic serving as the Alert Topic for CE
    Type: String
    AllowedPattern: '^arn:aws:sns:[a-z]{2}-[a-z]+-\d{1}:\d{12}:.*$'
    ConstraintDescription: Must be an SNS ARN

Conditions:
  IsProd:
    Fn::Equals:
      - Ref: AWS::AccountId
      - 196800776222
  IsUsEast1: !Equals [!Ref "AWS::Region", "us-east-1"]

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
        ENVIRONMENT: !Ref Environment
        LOGLEVEL: INFO
        INTEGRATIONS_BUCKET:
          !If [IsProd, "crm-integrations-prod", "crm-integrations-test"]
        CRM_API_URL: 
          !If [IsProd, "https://crm-api.impel.io", !Sub "https://crm-api-test.testenv.impel.io"]
        SECRET_KEY: "DEALERPEAK"
        UPLOAD_SECRET_KEY: "impel"
        CRM_API_DOMAIN: !If [IsProd, "crm-api.impel.io", "crm-api-test.testenv.impel.io"]
        SALES_AI_WEBHOOK: !If [IsProd, "", "https://webhook.site/7f3b6c6a-431c-4ca3-ab7f-eb1a6362b4cc"]
        CEAlertTopicArn: !Ref CEAlertTopicArn

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AccessSecretsManager
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/crm-integration-partner*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/crm-integration-partner*",
                    ]
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/crm-api*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/crm-api*",
                    ]
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: S3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource:
                  - !If [
                      IsProd,
                      "arn:aws:s3:::crm-integrations-prod/raw*",
                      "arn:aws:s3:::crm-integrations-test/raw*",
                    ]
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource:
                  - !If [
                      IsProd,
                      "arn:aws:s3:::crm-integrations-prod*",
                      "arn:aws:s3:::crm-integrations-test*"
                    ]
        - PolicyName: SQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource:
                  - !GetAtt InvokeDataPullQueue.Arn
                  - !GetAtt TransformDealerpeakDataQueue.Arn
                  - !GetAtt TransformUnifiedDataQueue.Arn
              - Effect: "Allow"
                Action:
                  - "sqs:SendMessage"
                Resource: "arn:aws:sqs:*:*:*"

  InvokeDataPull:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub dealerpeak-${Environment}-Invoke
      CodeUri: app/
      Handler: invoke_data_pull.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn

  InvokeDataPullErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub dealerpeak-${Environment}-Invoke
      AlarmDescription: Lambda invocation errors detected from the DealerPeak Invoke
      ActionsEnabled: true
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref InvokeDataPull
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900
      Statistic: Sum
      Threshold: 3
      TreatMissingData: notBreaching

  InvokeDataPullEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt InvokeDataPullQueue.Arn
      MaximumBatchingWindowInSeconds: 0
      FunctionName: !GetAtt InvokeDataPull.Arn

  InvokeDataPullQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dealerpeak-${Environment}-InvokeQueue"
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt InvokeDataPullDeadLetterQueue.Arn
        maxReceiveCount: 3

  InvokeDataPullDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dealerpeak-${Environment}-InvokeDLQ"
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 10

  InvokeDataPullDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmName: !Sub "dealerpeak-${Environment}-InvokeDLQ"
      AlarmDescription: There are messages in the DealerPeak Invoke DLQ
      ActionsEnabled: true
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
      Dimensions:
        - Name: QueueName
          Value: !GetAtt InvokeDataPullDeadLetterQueue.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 10
      TreatMissingData: notBreaching

  TransformDealerpeakData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub dealerpeak-${Environment}-TransformData
      CodeUri: app/
      Handler: transform_data.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn

  TransformDealerpeakDataEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt TransformDealerpeakDataQueue.Arn
      MaximumBatchingWindowInSeconds: 0
      FunctionName: !GetAtt TransformDealerpeakData.Arn

  TransformDealerpeakDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dealerpeak-${Environment}-TransformQueue"
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransformDealerpeakDataDeadLetterQueue.Arn
        maxReceiveCount: 3

  TransformDealerpeakDataDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dealerpeak-${Environment}-TransformDLQ"
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 10
  
  TransformDealerpeakDataDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmName: !Sub "dealerpeak-${Environment}-TransformDLQ"
      AlarmDescription: There are messages in the DealerPeak Transform DLQ
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering
      Dimensions:
        - Name: QueueName
          Value: !GetAtt TransformDealerpeakDataDeadLetterQueue.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 10
      TreatMissingData: notBreaching

  TransformDealerpeakDataQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref TransformDealerpeakDataQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt TransformDealerpeakDataQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt EventBridgeRule.Arn

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !If [IsProd, "crm-integrations-prod", "crm-integrations-test"]
          object:
            key:
              - { "prefix": "raw/dealerpeak/" }
      Targets:
        - Id: "TransformDealerpeakDataTarget"
          Arn: !GetAtt TransformDealerpeakDataQueue.Arn

  GetLeadUpdates:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub dealerpeak-${Environment}-LeadUpdates
      CodeUri: app/
      Handler: lead_updates.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn

  GetLeadUpdatesErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub dealerpeak-${Environment}-LeadUpdates
      AlarmDescription: Lambda invocation errors detected from the DealerPeak Lead Updates
      ActionsEnabled: true
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetLeadUpdates
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900
      Statistic: Sum
      Threshold: 3
      TreatMissingData: notBreaching
      
  SendActivityQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dealerpeak-${Environment}-SendActivityQueue"
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SendActivityDeadLetterQueue.Arn
        maxReceiveCount: 3
        
  SendActivityDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "dealerpeak-${Environment}-SendActivityDLQ"
      FifoQueue: true
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 10
  
  # TransformDealerpeakDataEventMapping:
  #   Type: AWS::Lambda::EventSourceMapping
  #   Properties:
  #     BatchSize: 10
  #     EventSourceArn: !GetAtt TransformDealerpeakDataQueue.Arn
  #     MaximumBatchingWindowInSeconds: 0
  #     FunctionName: !GetAtt TransformDealerpeakData.Arn
      
  SendActivity:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub dealerpeak-${Environment}-SendActivity
      CodeUri: app/
      Handler: send_activity.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn
      Events:
        SendActivityQueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt SendActivityQueue.Arn
            
  SendActivityDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub dealerpeak-${Environment}-SendActivityDLQ
      AlarmDescription: There are over 10 unprocessed messages in the Dead Letter Queue
      ActionsEnabled: true
      AlarmActions:
        - !Ref CEAlertTopicArn
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SendActivityDeadLetterQueue.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 10
      TreatMissingData: notBreaching