openapi: 3.0.0
info:
  version: "1.0.0"
  title: Impel Event Publishing API
  description: Event publishing API
  
servers:
  - description: Impel test environment
    url: https://8mdfapric6.execute-api.us-east-1.amazonaws.com/test

#{{API_AWS_VALIDATION}}
paths:
  /v1/events:
    post:
      tags:
        - Events
      description: Send events for publishing
      operationId: postEvents
      #{{POST_EVENTS_LAMBDA_INFO}}
      parameters:
        - "$ref": "#/components/parameters/clientId"
        - "$ref": "#/components/parameters/apiKey"
      responses:
        '200':
          description: Events successfully published.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventResponse"
        '400':
          "$ref": "#/components/responses/400"
        '401':
          "$ref": "#/components/responses/401"
        '500':
          "$ref": "#/components/responses/500"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"

components:
  responses:
    '400':
      description: This indicates Bad Request. For example this error can occur if
        a required property in the request JSON is missing.
    '401':
      description: This request is unauthorized. The authorization credentials are
        missing or are wrong.
    '500':
      description: Internal Server Error. Please contact Impel support.

  schemas:
    Event:
      type: object
      properties:
        event_json:
          type: array
          description: Events
          items:
            description: Event payload
            type: object
        event_source:
          type: string
          description: The source from which the event originated.
    EventResponse:
      type: array
      description: Event payloads matched with response from event bridge.
      items:
        type: object
        properties:
          event_json:
            type: object
            description: Event payload
          event_bus_id:
            type: string
            description: A unique identifier (e.g., UUID) for an event generated by the event bus.
            example: "009a352b-d6b5-405b-8c3f-36ccd16aa431"
          error_code:
            type: string
            description: Error code from event bridge related to the event.
          error_message:
            type: string
            description: Error message from event bridge related to the event.

  parameters:
    clientId:
      name: client-id
      in: header
      description: This parameter uniquely identifies an Impel client and will be used for API authentication and authorization.
      required: true
      schema:
        type: string
    apiKey:
      name: api-key
      in: header
      description: An API Key provided by Impel that will be used for API authentication and authorization.
      required: true
      schema:
        type: string