AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: adf assembler

Parameters:
    Environment:
        Description: The name of the runtime environment
        Type: String
        AllowedPattern: "^[a-zA-Z0-9-]+$"
        ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens

Conditions:
    IsProd:
        Fn::Equals:
            - Ref: AWS::AccountId
            - "196800776222"

Globals:
    Function:
        Runtime: python3.9
        Environment:
            Variables:
                AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
                ENVIRONMENT: !Ref Environment
                LOGLEVEL: INFO
                SNS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
                INTEGRATIONS_BUCKET: 
                    !If [
                        IsProd,
                        "crm-integrations-prod",
                        "crm-integrations-test",
                    ]
                ADF_SENDER_EMAIL_ADDRESS: 
                    !If [
                        IsProd,
                        "crm.adf@impel.ai",
                        "lesakia@impel.ai",
                    ]
                UPLOAD_SECRET_KEY: "impel"
                CRM_API_DOMAIN:
                    !If [
                        IsProd,
                        "crm-api.impel.io",
                        "crm-api-test.testenv.impel.io",
                    ]

Resources:
    LambdaRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Policies:
                - PolicyName: CloudWatchLogsPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action:
                                - "logs:CreateLogGroup"
                                - "logs:CreateLogStream"
                                - "logs:PutLogEvents"
                            Resource: "arn:aws:logs:*:*:*"
                - PolicyName: AccessSecretsManager
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action:
                                - secretsmanager:GetSecretValue
                            Resource:
                                - !If [
                                      IsProd,
                                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/crm-api*",
                                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/crm-api*",
                                  ]
                                - !If [
                                    IsProd,
                                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/crm-integrations-partner*",
                                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/crm-integrations-partner*",
                                ]
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action:
                                - "lambda:InvokeFunction"
                            Resource: "*"
                - PolicyName: S3Policy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action:
                                - "s3:GetObject"
                                - "s3:PutObject"
                            Resource:
                                - !Sub "arn:aws:s3:::crm-integrations-${Environment}*"
                                - !Sub "arn:aws:s3:::email-service-store-${Environment}*"
                - PolicyName: SNSPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action:
                                - "sns:Publish"
                            Resource:
                                - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
                - PolicyName: SQSPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                      - Effect: "Allow"
                        Action:
                        - "sqs:SendMessage"
                        - "sqs:ReceiveMessage"
                        - "sqs:DeleteMessage"
                        - "sqs:GetQueueAttributes"
                        Resource:
                        - !GetAtt AdfAssemblerQueue.Arn
                        - !GetAtt AdfAssemblerDeadLetterQueue.Arn
                        - !GetAtt OemAdfAssemblerQueue.Arn
                        - !GetAtt OemAdfAssemblerDeadLetterQueue.Arn
                - PolicyName: EventRoutingBusAccess
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                        - Effect: "Allow"
                          Action:
                          - "events:PutEvents"
                          Resource:
                          - !If [
                              IsProd,
                              !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/crm-shared-prod-CrmEventBus",
                              !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/crm-shared-test-CrmEventBus"
                          ]

    AdfAssembler:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "adf-assembler-${Environment}"
            CodeUri: app/
            Handler: standard_adf_assembler.lambda_handler
            Timeout: 30
            Role: !GetAtt LambdaRole.Arn

    AdfAssemblerQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub "adf-assembler-${Environment}-AdfAssemblerQueue"
            VisibilityTimeout: 60
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt AdfAssemblerDeadLetterQueue.Arn
                maxReceiveCount: 3

    AdfAssemblerDeadLetterQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub "adf-assembler-${Environment}-AdfAssemblerDLQ"
            MessageRetentionPeriod: 604800
            VisibilityTimeout: 10

    AdfAssemblerEventMapping:
        Type: AWS::Lambda::EventSourceMapping
        Properties:
            BatchSize: 1
            EventSourceArn: !GetAtt AdfAssemblerQueue.Arn
            MaximumBatchingWindowInSeconds: 0
            FunctionName: !GetAtt AdfAssembler.Arn

    AdfAssemblerDLQAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub "adf-assembler-${Environment}-AdfAssemblerDLQ"
            AlarmDescription: Triggered when Standard ADF DLQ has more than 1 unprocessed message
            ActionsEnabled: true
            AlarmActions:
                - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
            Dimensions:
                - Name: QueueName
                  Value: !GetAtt AdfAssemblerDeadLetterQueue.QueueName
            EvaluationPeriods: 1
            MetricName: ApproximateNumberOfMessagesVisible
            Namespace: AWS/SQS
            Period: 300
            Statistic: Sum
            ComparisonOperator: GreaterThanThreshold
            Threshold: 1
            TreatMissingData: notBreaching

    OemAdfAssembler:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "oem-adf-assembler-${Environment}"
            CodeUri: app/
            Handler: oem_adf_assembler.lambda_handler
            Timeout: 30
            Role: !GetAtt LambdaRole.Arn

    OemAdfAssemblerQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub "oem-adf-assembler-${Environment}-OemAdfAssemblerQueue"
            VisibilityTimeout: 60
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt OemAdfAssemblerDeadLetterQueue.Arn
                maxReceiveCount: 3

    OemAdfAssemblerDeadLetterQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub "oem-adf-assembler-${Environment}-OemAdfAssemblerDLQ"
            MessageRetentionPeriod: 604800
            VisibilityTimeout: 10

    OemAdfAssemblerEventMapping:
        Type: AWS::Lambda::EventSourceMapping
        Properties:
            BatchSize: 1
            EventSourceArn: !GetAtt OemAdfAssemblerQueue.Arn
            MaximumBatchingWindowInSeconds: 0
            FunctionName: !GetAtt OemAdfAssembler.Arn

    OemAdfAssemblerDLQAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub "oem-adf-assembler-${Environment}-OemAdfAssemblerDLQ"
            AlarmDescription: Triggered when OEM ADF DLQ has more than 1 unprocessed message
            ActionsEnabled: true
            AlarmActions:
                - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
            Dimensions:
                - Name: QueueName
                  Value: !GetAtt OemAdfAssemblerDeadLetterQueue.QueueName
            EvaluationPeriods: 1
            MetricName: ApproximateNumberOfMessagesVisible
            Namespace: AWS/SQS
            Period: 300
            Statistic: Sum
            ComparisonOperator: GreaterThanThreshold
            Threshold: 1
            TreatMissingData: notBreaching  
