AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: shared crm resources

Parameters:
  Environment:
    Description: The name of the runtime environment
    Type: String
    AllowedPattern: "^[a-zA-z0-9-]+$"
    ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens

Conditions:
  IsProd:
    Fn::Equals:
      - Ref: AWS::AccountId
      - 196800776222
  IsUsEast1: !Equals [!Ref "AWS::Region", "us-east-1"]

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
        ENVIRONMENT: !Ref Environment
        LOGLEVEL: INFO
        CRM_API_URL:
          !If [IsProd, "https://crm-api.impel.io/", "https://crm-api-test.testenv.impel.io/"]
        CRM_API_SECRET_KEY: !If [IsProd, "impel", "test"]
        CRM_EVENT_BUS_NAME: !Ref CrmEventBus
        PARTNER_ID_MAPPINGS: |
          {
            "dealerpeak": "internal_dealerpeak",
            "tekion": "internal_tekion",
            "pbs": "internal_pbs"
          }

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: S3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource:
                - !Sub "arn:aws:s3:::crm-integrations-${Environment}/configurations*"
        - PolicyName: SQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sqs:SendMessage"
                Resource: "arn:aws:sqs:*:*:*"
              - Effect: "Allow"
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource:
                - !GetAtt ProcessLeadUpdatesQueue.Arn
                - !GetAtt EventEnricherQueue.Arn
        - PolicyName: AccessSecretsManager
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/crm-api*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/crm-api*",
                    ]
        - PolicyName: EventBridgePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "events:PutEvents"
                Resource: !GetAtt CrmEventBus.Arn

  GetActiveDealers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub crm-shared-${Environment}-GetActiveDealers
      CodeUri: app/
      Handler: get_active_dealers.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          INTEGRATIONS_BUCKET: !Ref IntegrationsBucket

  GetActiveDealersErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub crm-shared-${Environment}-GetActiveDealers
      AlarmDescription: Get Active Dealers failed 3 times within 15 minutes
      ActionsEnabled: true
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetActiveDealers
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900
      Statistic: Sum
      Threshold: 3
      TreatMissingData: notBreaching

  ScheduledCRMDataPull:
    Type: AWS::Events::Rule
    Properties:
      Description: "Scheduled CRM Data Pull"
      ScheduleExpression: "cron(*/5 * * * ? *)"
      State: !If [IsProd, "ENABLED", "DISABLED"]
      Targets:
        - Arn: !GetAtt GetActiveDealers.Arn
          Id: "get_active_dealers_dealerpeak"
          Input: '{"impel_integration_partner_name": "DEALERPEAK", "partner_id": "internal_dealerpeak"}'
        - Arn: !GetAtt GetActiveDealers.Arn
          Id: "get_active_dealers_pbs"
          Input: '{"impel_integration_partner_name": "PBS", "partner_id": "internal_pbs"}'
        - Arn: !GetAtt GetActiveDealers.Arn
          Id: "get_active_dealers_tekion"
          Input: '{"impel_integration_partner_name": "TEKION", "partner_id": "internal_tekion"}'

  ScheduledCRMDataPullLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GetActiveDealers.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledCRMDataPull.Arn

  IntegrationsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "crm-integrations-${Environment}"
      NotificationConfiguration:
        EventBridgeConfiguration:
            EventBridgeEnabled: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireNoncurrent
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3  # A very generous limit unlikely to cause problems with virtually any of our use cases.
            ExpiredObjectDeleteMarker: True  # Must be set to avoid excess AWS Backup costs.
            NoncurrentVersionExpiration:
              NoncurrentDays: 3  # A very short limit to avoid excess bucket costs.
            Status: Enabled
      VersioningConfiguration:
        Status: !If [IsProd, Enabled, Suspended]
      Tags:
        - Key: org:backup-tier
          Value: !If [ IsProd, 'medium', 'none' ]

  ProcessLeadUpdates:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "crm-shared-${Environment}-LeadUpdates"
      CodeUri: app/
      Handler: process_lead_updates.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn

  ProcessLeadUpdatesEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt ProcessLeadUpdatesQueue.Arn
      MaximumBatchingWindowInSeconds: 30
      FunctionName: !GetAtt ProcessLeadUpdates.Arn

  ProcessLeadUpdatesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "crm-shared-${Environment}-LeadUpdatesQueue"
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessLeadUpdatesDeadLetterQueue.Arn
        maxReceiveCount: 3

  ProcessLeadUpdatesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "crm-shared-${Environment}-LeadUpdatesDLQ"
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 10

  EventEnricher:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub crm-shared-${Environment}-EventEnricher
      CodeUri: app/
      Handler: event_enricher.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn

  EventEnricherQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "crm-shared-${Environment}-EventEnricherQueue"
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessLeadUpdatesDeadLetterQueue.Arn
        maxReceiveCount: 3

  EventEnricherDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "crm-shared-${Environment}-EventEnricherDLQ"
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 10

  EventEnricherDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "crm-shared-${Environment}-EventEnricherDLQAlarm"
      AlarmDescription: There are over 1 unprocessed messages in the EventEnricherDLQ
      ActionsEnabled: !If [ IsProd, true, false ]
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering
      Dimensions:
        - Name: QueueName
          Value: !GetAtt EventEnricherDeadLetterQueue.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      TreatMissingData: notBreaching

  EventEnricherEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt EventEnricherQueue.Arn
      MaximumBatchingWindowInSeconds: 0
      FunctionName: !GetAtt EventEnricher.Arn

  CrmEventBusRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CrmEventBusPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !GetAtt CrmEventBus.Arn
        - PolicyName: CrmEventBusDLQPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt CrmEventBusDLQ.Arn
        - PolicyName: DealPeakQueuePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  Fn::ImportValue: !Sub "dealerpeak-${Environment}-SendActivityQueueArn"
        - PolicyName: DealerPeakDLQPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  Fn::ImportValue: !Sub "dealerpeak-${Environment}-SendActivityDLQArn"

  CrmEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub 'crm-shared-${Environment}-CrmEventBus'
      DeadLetterConfig:
        Arn: !GetAtt CrmEventBusDLQ.Arn
      Description: Event bus for the IDP Shared Services

  CrmEventBusDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "crm-shared-${Environment}-CrmEventBusDLQ"
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300

  CrmEventBusDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "crm-shared-${Environment}-CrmEventBusDLQAlarm"
      AlarmDescription: Events failed to be processed by the CRM Event Bus
      ActionsEnabled: !If [ IsProd, true, false ]
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering
      Dimensions:
        - Name: QueueName
          Value: !GetAtt CrmEventBusDLQ.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      TreatMissingData: notBreaching

  DealerpeakEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "crm-shared-${Environment}-DealerpeakEventRule"
      EventPattern:
        source:
          - "EventEnricher"
        detail:
          event_type:
            - "Activity Created"
          partner_name:
            - "DEALERPEAK"
      State: ENABLED
      EventBusName: !Ref CrmEventBus
      Targets:
        - Id: DealerPeakQueue
          Arn:
            Fn::ImportValue: !Sub "dealerpeak-${Environment}-SendActivityQueueArn"
          DeadLetterConfig:
            Arn:
              Fn::ImportValue: !Sub "dealerpeak-${Environment}-SendActivityDLQArn"
          RoleArn: !GetAtt CrmEventBusRole.Arn
    
  MonitoringRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "crm-shared-${Environment}-MonitoringRule"
      EventPattern:
        source:
          - "EventEnricher"
      State: ENABLED
      EventBusName: !Ref CrmEventBus
      Targets:
        - Id: Lambda
          Arn: !GetAtt MonitoringLambda.Arn

  MonitoringInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MonitoringLambda
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt MonitoringRule.Arn

  MonitoringLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "crm-shared-${Environment}-MonitoringLambda"
      CodeUri: app/
      Handler: monitoring.lambda_handler
      Role: !GetAtt LambdaRole.Arn

Outputs:
  EventEnricherQueueUrl:
    Description: URL of the EventEnricherQueue
    Value: !Ref EventEnricherQueue
    Export:
      Name: !Sub "crm-shared-${Environment}-EventEnricherQueueUrl"