DEALERSPIKE_TAGS = [
    "id",
    "dealerid",
    "stock_number",
    "make",
    "model",
    "year",
    "retailprice",
    "clutch",
    "location",
    "modifieddate",
    "vin",
    "airconditioners",
    "isselfcontained",
    "haslevelingjacks",
    "issalespending",
    "lengthininches",
    "istoyhauler",
    "displayorder",
    "vehtype",
    "bodysubtype",
    "url",
    "images",
    "classid",
    "condition",
    "price",
    "msrp",
    "accessories",
    "noteshtml",
    "dealername",
    "address",
    "city",
    "state",
    "zipcode",
    "telephone",
    "email",
    "iscustom",
    "isclearance",
    "isconsignment",
    "isfeatured",
    "enginehours",
    "horsepower",
    "color",
    "description",
    "miles",
    "imageoverlaytext",
    "torque",
    "transmission",
    "category_name",
    "fueltype",
    "family",
    "status",
    "propulsion",
    "enginetext",
    "brand",
    "displacement",
    "weight",
]

ARI_TAGS = [
    "id", "title", "link", "description", "price", "price_type", "stocknumber", "vin",
    "manufacturer", "year", "color", "model_type", "model_typestyle", "model_name",
    "trim_name", "trim_color", "condition", "usage", "location", "updated",
    "metric_type", "metric_value", "images", "attributes"
]

def get_headers(provider):
    if provider == 'dealerspike':
        return DEALERSPIKE_TAGS
    if provider == 'ari':
        return ARI_TAGS
    raise RuntimeError(f"Unsupported web provider: {provider}")