DEALERSPIKE_CONFIG = {
    "provider": "dealerspike",
    "tag": "item",
    "headers": [
        "id",
        "dealerid",
        "stock_number",
        "make",
        "model",
        "year",
        "retailprice",
        "clutch",
        "location",
        "modifieddate",
        "vin",
        "airconditioners",
        "isselfcontained",
        "haslevelingjacks",
        "issalespending",
        "lengthininches",
        "istoyhauler",
        "displayorder",
        "vehtype",
        "bodysubtype",
        "url",
        "images",
        "classid",
        "condition",
        "price",
        "msrp",
        "accessories",
        "noteshtml",
        "dealername",
        "address",
        "city",
        "state",
        "zipcode",
        "telephone",
        "email",
        "iscustom",
        "isclearance",
        "isconsignment",
        "isfeatured",
        "enginehours",
        "horsepower",
        "color",
        "description",
        "miles",
        "imageoverlaytext",
        "torque",
        "transmission",
        "category_name",
        "fueltype",
        "family",
        "status",
        "propulsion",
        "enginetext",
        "brand",
        "displacement",
        "weight",
        "miles",
    ],
}

ARI_CONFIG = {
    "provider": "ari",
    "tag": "item",
    "headers": [
        "id",
        "title",
        "link",
        "description",
        "price",
        "price_type",
        "stocknumber",
        "vin",
        "manufacturer",
        "year",
        "color",
        "model_type",
        "model_typestyle",
        "model_name",
        "trim_name",
        "trim_color",
        "condition",
        "usage",
        "location",
        "updated",
        "metric_type",
        "metric_value",
        "images",
        "attributes",
    ],
}

DX1_CONFIG = {
    "provider": "dx1",
    "tag": ".//listing",
    "headers": [
        "listing-photos",
        "stock-number",
        "location",
        "price",
        "condition",
        "type",
        "category",
        "description-long",
        "listing-url",
        "vin",
        "color-primary",
        "model-year",
        "manufacturer",
        "model",
        "listing-id",
        "description-short",
        "miles",
        "specifications",
    ],
}


def get_provider_config(provider):
    """Get the config for a given provider."""
    if provider == "dealerspike":
        return DEALERSPIKE_CONFIG
    if provider == "ari":
        return ARI_CONFIG
    if provider == "dx1":
        return DX1_CONFIG
    raise RuntimeError(f"Unsupported web provider: {provider}")
