name: Find Changed Services Action
description: Find changed services in a pull request or push event

outputs:
  changed_services:
    description: "List of changed services" 
    value: ${{ steps.changed-services.outputs.changed_services }}

runs:
  using: 'composite'
  steps:
    - name: Get changed files
      uses: ./.github/actions/find_changed_files/
      id: find-changed-files

    - name: Get changed services
      id: find-changed-services
      run: |
        CHANGED_SERVICES=""
        for file in ${{ steps.find-changed-files.outputs.changed_files }}; do
          DIR_NAME=$(dirname $file)
          while [ "$DIR_NAME" != "." ]; do
            if [ -f "$DIR_NAME/template.yaml" ]; then
              if [[ ! "$CHANGED_SERVICES" == *"$DIR_NAME"* ]]; then
                echo "Adding $DIR_NAME to changed services"
                CHANGED_SERVICES="$DIR_NAME $CHANGED_SERVICES "
              fi
              break
            fi
            DIR_NAME=$(dirname $DIR_NAME)
          done
        done
        echo "CHANGED_SERVICES: $CHANGED_SERVICES"
        echo "changed_services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT
      shell: bash