AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: tekion crm integration

Parameters:
  Environment:
    Description: The name of the runtime environment
    Type: String
    AllowedPattern: "^[a-zA-z0-9-]+$"
    ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens

Conditions:
  IsProd:
    Fn::Equals:
      - Ref: AWS::AccountId
      - 196800776222

Globals:
  Function:
    Runtime: python3.12
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
        REGION: !Sub "${AWS::Region}"
        SECRET_MANAGER_ID: 'TEKION'
        PARTNER_KEY: "TEKION"
        POWERTOOLS_SERVICE_NAME: token-rotation
        POWERTOOLS_LOG_LEVEL: !If [IsProd, "INFO", "DEBUG"]
        INTEGRATIONS_BUCKET: !Sub "crm-integrations-${Environment}"


Resources:
  TekionTokenRotationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: S3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource:
                  - !If [
                    IsProd,
                    !Sub "arn:aws:s3:::auth-service-${AWS::Region}-prod*",
                    !Sub "arn:aws:s3:::auth-service-${AWS::Region}-test*"
                  ]
        - PolicyName: SQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sqs:SendMessage"
                Resource: "arn:aws:sqs:*:*:*"
              - Effect: "Allow"
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource:
                  - !GetAtt TekionTokenRotationQueue.Arn
        - PolicyName: AccessSecretsManager
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !If [
                    IsProd,
                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/crm-tekion*",
                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/crm-tekion*"
                  ]

  TekionTokenRotationQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TekionTokenRotationQueueDLQ

  TekionTokenRotationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'tekion-token-rotation-failures-queue-${Environment}'
      VisibilityTimeout: 3600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TekionTokenRotationQueueDLQ.Arn
        maxReceiveCount: 1

  TekionTokenRotationFunctionRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Nightly trigger for InvokeTekionTokenRotationFunction
      ScheduleExpression: cron(0 22 * * ? *)  # Schedule for 10pm UTC every day
      State: !If [IsProd, "ENABLED", "DISABLED"]
      Targets:
        - Id: "TekionTokenRotationQueue"
          Arn: !GetAtt TekionTokenRotationQueue.Arn


  TekionTokenRotationEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt TekionTokenRotationQueue.Arn
      MaximumBatchingWindowInSeconds: 1
      FunctionName: !GetAtt InvokeTekionTokenRotationFunction.Arn

  InvokeTekionTokenRotationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Invoke Tekion's token rotation
      Role: !GetAtt TekionTokenRotationRole.Arn
      CodeUri: app/
      Runtime: python3.12
      Handler: access_token.lambda_handler
      Timeout: 180
      Policies:
        - Id: FunctionPermissions
          Version: "2012-10-17"
          Statement:
            - Sid: AllowS3
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !If [ IsProd,
                  !Sub "arn:aws:s3:::auth-service-${AWS::Region}-prod/*",
                  !Sub "arn:aws:s3:::auth-service-${AWS::Region}-test/*"
                ]
            - Sid: AllowSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !If [ IsProd,
                  !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/crm-integrations-partner*",
                  !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/crm-integrations-partner*",
                ]
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  InvokeTekionTokenRotationErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub tekion-token-rotation-error-${Environment}
      AlarmDescription: There are messages in the Tekion token rotation error
      ActionsEnabled: true
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
      Dimensions:
        - Name: FunctionName
          Value: !Ref InvokeTekionTokenRotationFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900
      Statistic: Sum
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  TekionTokenRotationQueueDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmName: !Sub TekionTokenRotationQueueDLQ-${Environment}
      AlarmDescription: There are messages in the Tekion token rotation order DLQ
      ActionsEnabled: true
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
      Dimensions:
        - Name: QueueName
          Value: !GetAtt TekionTokenRotationQueueDLQ.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      TreatMissingData: notBreaching
