openapi: 3.0.0
info:
  title: CDPI API
  version: 1.0.0
  description: API for CDPI
paths:
  /dealer:
    get:
      summary: Retrieve a list of dealers with optional filters
      description: >
        Retrieve dealer records. If no query parameters are provided, all dealers are returned.
        You can filter by fields such as dealer_name, sfdc_account_id, salesai_dealer_id,
        or serviceai_dealer_id. Supports pagination via 'page' and 'limit' parameters.
      parameters:
        - in: query
          name: dealer_name
          schema:
            type: string
          description: Filter by dealer name.
        - in: query
          name: sfdc_account_id
          schema:
            type: string
          description: Filter by SFDC account ID.
        - in: query
          name: salesai_dealer_id
          schema:
            type: string
          description: Filter by SalesAI dealer ID.
        - in: query
          name: serviceai_dealer_id
          schema:
            type: string
          description: Filter by ServiceAI dealer ID.
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: The page number for pagination (default is 1).
        - in: query
          name: limit
          schema:
            type: integer
            default: 100
          description: The maximum number of records to return per page (default is 100).
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DealerFunction.Arn}/invocations
        passthroughBehavior: never
        httpMethod: POST
        type: aws_proxy
      responses:
        '200':
          description: A paginated list of dealer records.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealerListResponse'
        '400':
          description: Invalid request parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new dealer.
      description: Create a new dealer record along with its integration partner details.
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DealerFunction.Arn}/invocations
        passthroughBehavior: never
        httpMethod: POST
        type: aws_proxy
      requestBody:
        description: Dealer creation payload.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DealerCreateRequest'
      responses:
        '201':
          description: Dealer created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealerCreatedResponse'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update an existing dealer.
      description: Update the details of an existing dealer.
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DealerFunction.Arn}/invocations
        passthroughBehavior: never
        httpMethod: POST
        type: aws_proxy
      requestBody:
        description: Dealer update payload.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DealerUpdateRequest'
      responses:
        '200':
          description: Dealer updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dealer'
        '400':
          description: Invalid input or dealer not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Dealer:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the dealer.
        dealer_name:
          type: string
          description: The dealer's name.
        sfdc_account_id:
          type: string
          description: Salesforce account identifier.
        salesai_dealer_id:
          type: string
          description: SalesAI dealer identifier.
        serviceai_dealer_id:
          type: string
          description: ServiceAI dealer identifier.
        db_creation_date:
          type: string
          format: date-time
          description: Timestamp when the record was created.
        db_update_date:
          type: string
          format: date-time
          description: Timestamp when the record was last updated.
      required:
        - id
        - dealer_name
        - sfdc_account_id
        - salesai_dealer_id
        - serviceai_dealer_id
    DealerCreateRequest:
      type: object
      properties:
        dealer_name:
          type: string
          description: The dealer's name.
        sfdc_account_id:
          type: string
          description: Salesforce account identifier.
        salesai_dealer_id:
          type: string
          description: SalesAI dealer identifier.
        serviceai_dealer_id:
          type: string
          description: ServiceAI dealer identifier.
        cdp_dealer_id:
          type: string
          description: Custom dealer identifier.
        impel_integration_partner_name:
          type: string
          description: Integration partner name for the dealer (e.g., FORD_DIRECT).
      required:
        - dealer_name
        - sfdc_account_id
        - salesai_dealer_id
        - serviceai_dealer_id
        - cdp_dealer_id
        - impel_integration_partner_name
    DealerUpdateRequest:
      type: object
      properties:
        dealer_id:
          type: integer
          description: Unique identifier for the dealer to update.
        dealer_name:
          type: string
          description: The dealer's name.
        sfdc_account_id:
          type: string
          description: Salesforce account identifier.
        salesai_dealer_id:
          type: string
          description: SalesAI dealer identifier.
        serviceai_dealer_id:
          type: string
          description: ServiceAI dealer identifier.
        cdp_dealer_id:
          type: string
          description: Custom dealer identifier.
        impel_integration_partner_name:
          type: string
          description: Integration partner name for the dealer.
      required:
        - dealer_id
    DealerListResponse:
      type: object
      properties:
        page:
          type: integer
          description: Current page number.
        limit:
          type: integer
          description: Maximum number of records returned per page.
        dealers:
          type: array
          items:
            $ref: '#/components/schemas/Dealer'
        has_next_page:
          type: boolean
          description: Flag indicating if there is a next page.
      required:
        - page
        - limit
        - dealers
        - has_next_page
    DealerCreatedResponse:
      type: object
      properties:
        message:
          type: string
          description: Confirmation message.
        dealer_id:
          type: integer
          description: Unique identifier of the created dealer.
      required:
        - message
        - dealer_id
    DealerDeleteRequest:
      type: object
      properties:
        dealer_id:
          type: integer
          description: Unique identifier for the dealer to delete.
      required:
        - dealer_id
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A human-readable error message.
        errors:
          type: string
          description: Additional error details.
      required:
        - message
