AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quiter DMS ETL

Parameters:
  Environment:
    Description: The name of the runtime environment
    Type: String
    AllowedPattern: '^[a-zA-z0-9-]+$'
    ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens
  CEAlertTopicArn:
    Description: The ARN of the SNS topic serving as the Alert Topic for CE
    Type: String
    AllowedPattern: '^arn:aws:sns:[a-z]{2}-[a-z]+-\d{1}:\d{12}:.*$'
    ConstraintDescription: Must be an SNS ARN

Conditions:
  IsProd:
    Fn::Equals:
    - Ref: AWS::AccountId
    - 196800776222
  IsUsEast1: !Equals [ !Ref 'AWS::Region', 'us-east-1' ]

Mappings:
  Subnets:
    us-east-1:
      '196800776222':
        - subnet-0d29a385efe83bf1c
        - subnet-0e88ecdd743701e96
        - subnet-00291e028e21cb78f
        - subnet-0b1555d5fa3c8ba8e
      '143813444726':
        - subnet-030d57e39ec0df603
        - subnet-01044d580678ea63c
        - subnet-0b29db0aeb6cdabec
        - subnet-0e28d592f2ca28fb7
  VpcId:
    us-east-1:
      '196800776222': vpc-03417e688cee5bc07
      '143813444726': vpc-0b28df8980a1905d5

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Sub '${AWS::AccountId}'
        REGION: !Sub '${AWS::Region}'
        ENVIRONMENT: !Ref Environment
        IS_PROD: !If [ IsProd, 1, 0 ]
        LOGLEVEL: INFO
        INTEGRATIONS_BUCKET: !If [ IsProd,
          !Sub "integrations-${AWS::Region}-prod",
          !Sub "integrations-${AWS::Region}-test"
        ]
        INVOKE_QUEUE: !Ref InvokeQueue
        MERGE_REPAIR_ORDER_QUEUE: !Ref QuiterMergeRepairOrderQueue
        MERGE_APPOINTMENT_QUEUE: !Ref QuiterMergeAppointmentQueue
        MERGE_VEHICLE_SALE_QUEUE: !Ref QuiterMergeVehicleSaleQueue
        FORMAT_APPOINTMENT_QUEUE: !Ref QuiterFormatAppointmentQueue
        CE_TOPIC: !Ref CEAlertTopicArn
    VpcConfig:
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetIds: !FindInMap [ Subnets, !Ref 'AWS::Region', !Ref 'AWS::AccountId' ]

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    Properties:
      GroupDescription: Permit traffic from the Quiter integration service
      VpcId: !FindInMap [ VpcId, !Ref 'AWS::Region', !Ref 'AWS::AccountId']
      SecurityGroupEgress:
        - Description: AllowAll
          CidrIp: 0.0.0.0/0
          IpProtocol: '-1'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Product
          Value: quiter-integration

  RDSInboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Quiter integration rds access
      GroupId: !If [ IsProd,
                      'sg-00e12bc4c116eb820',
                      'sg-00b911ee260ce5153'
                    ]
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId
  
  InvokeQuiterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Invoke data pull for every Quiter dealer
      CodeUri: app/
      Handler: invoke_quiter.lambda_handler
      Timeout: 180
      Policies:
        - Id: FunctionPermissions
          Version: "2012-10-17"
          Statement:
            - Sid: AllowSQS
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt InvokeQueue.Arn
            - Sid: AllowSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !If [ IsProd,
                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/DmsDataService*",
                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/DmsDataService*",
                  ]
      Environment:
        Variables:
          Environment: !Ref Environment
          INVOKE_QUEUE: !Ref InvokeQueue
      Events:
        DailyInvoke:
          Type: Schedule
          Properties:
            Description: Start the daily data pull for each quiter dealer.
            Enabled: !If [ IsProd, true, false ]
            Schedule: cron(0 12 * * ? *)  # Daily at 12:00 UTC
            Input: '{"frequency": "daily"}'
  
  InvokeQuiterFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if Invoke Quiter function fails"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref InvokeQuiterFunction
      Statistic: Sum
      Period: 900  # 15 minutes
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering
      ActionsEnabled: !If [IsProd, true, false]

  InvokeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub quiter-${Environment}-InvokeQueue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt InvokeQueueDLQ.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 900

  InvokeQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub quiter-${Environment}-InvokeQueueDLQ

  InvokeQueueDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub quiter-${Environment}-InvokeQueueDLQAlarm
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: !GetAtt InvokeQueueDLQ.QueueName
      Statistic: Sum
      Period: 900  # 15 minutes
      EvaluationPeriods: 1
      Threshold: 1  # Trigger alarm if there is at least 1 message in DLQ
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering
      ActionsEnabled: !If [IsProd, true, false]

  ExtractDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Extract Quiter Data From FTP
      CodeUri: app/
      Handler: extract_data.lambda_handler
      Timeout: 900
      Policies:
        - Id: FunctionPermissions
          Version: "2012-10-17"
          Statement:
            - Sid: AllowSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !If [ IsProd,
                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/QuiterFTP*",
                    !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/QuiterFTP*",
                  ]
            - Sid: AllowS3
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
                - s3:*Object
              Resource:
                - !If [ IsProd,
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-prod/*",
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-test/*"
                  ]
            - Sid: AllowSNSPolicy
              Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
            - Sid: AllowSQS
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt QuiterMergeAppointmentQueue.Arn
                - !GetAtt QuiterMergeRepairOrderQueue.Arn
                - !GetAtt QuiterMergeVehicleSaleQueue.Arn
      Environment:
        Variables:
          Environment: !Ref Environment
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: True
            Queue: !GetAtt InvokeQueue.Arn

  QuiterMergeRepairOrderQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 3600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt QuiterMergeRepairOrderDLQ.Arn
        maxReceiveCount: 5

  QuiterMergeRepairOrderDLQ:
    Type: AWS::SQS::Queue

  QuiterMergeAppointmentQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "quiter-${Environment}-MergeAppointmentsQueue"
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt QuiterMergeAppointmentDeadLetterQueue.Arn
        maxReceiveCount: 3

  QuiterMergeAppointmentDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "quiter-${Environment}-MergeAppointmentsDLQ"
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 10

  QuiterMergeVehicleSaleQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 3600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt QuiterMergeVehicleSaleDLQ.Arn
        maxReceiveCount: 5

  QuiterMergeVehicleSaleDLQ:
    Type: AWS::SQS::Queue

  QuiterMergeAppointment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub quiter-${Environment}-MergeAppointments
      CodeUri: app/
      Handler: quiter_merge_appointments.merge_appointments.lambda_handler
      Timeout: 900
      MemorySize: 512
      Policies:
        - Id: FunctionPermissions
          Version: "2012-10-17"
          Statement:
            - Sid: AllowS3
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
                - s3:*Object
              Resource:
                - !If [ IsProd,
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-prod/*",
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-test/*"
                  ]
                - !If [ IsProd,
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-prod",
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-test"
                  ]
            - Sid: AllowSNSPolicy
              Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
            - Sid: AllowSQS
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt QuiterFormatAppointmentQueue.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: True
            Queue: !GetAtt QuiterMergeAppointmentQueue.Arn

  MergeAppointmentsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/quiter-${Environment}-MergeAppointments"

  # QuiterMergeAppointmentEventMapping:
  #   Type: AWS::Lambda::EventSourceMapping
  #   Properties:
  #     BatchSize: 10
  #     EventSourceArn: !GetAtt QuiterMergeAppointmentQueue.Arn
  #     MaximumBatchingWindowInSeconds: 0
  #     FunctionName: !GetAtt QuiterMergeAppointment.Arn

  # MergeAppointmentsDLQAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmName: !Sub "quiter-${Environment}-MergeAppointmentsDLQ"
  #     AlarmDescription: There are over 1 unprocessed messages in the Quiter Merge Appointments DLQ
  #     ActionsEnabled: true
  #     AlarmActions:
  #       - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
  #     Dimensions:
  #       - Name: QueueName
  #         Value: !GetAtt MergeAppointmentsDeadLetterQueue.QueueName
  #     EvaluationPeriods: 1
  #     MetricName: ApproximateNumberOfMessagesVisible
  #     Namespace: AWS/SQS
  #     Period: 300
  #     Statistic: Sum
  #     ComparisonOperator: GreaterThanThreshold
  #     Threshold: 1
  #     TreatMissingData: notBreaching

  QuiterFormatInsertFilesAppointment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub quiter-${Environment}-QuiterFormatInsertFilesAppointment
      CodeUri: app/
      Handler: quiter_merge_appointments.format_appointment.lambda_handler
      Timeout: 60
      MemorySize: 256
      Policies:
        - Id: FunctionPermissions
          Version: "2012-10-17"
          Statement:
            - Sid: AllowS3
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
                - s3:*Object
              Resource:
                - !If [ IsProd,
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-prod/*",
                    !Sub "arn:aws:s3:::integrations-${AWS::Region}-test/*"
                  ]
            - Sid: AllowSNSPolicy
              Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
            - Sid: AllowSQS
              Effect: Allow
              Action:
                - sqs:ReceiveMessage
              Resource:
                - !GetAtt QuiterFormatAppointmentQueue.Arn
            - Sid: AllowGetDBInfo
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !If [ IsProd,
                          !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/DMSDB*",
                          !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/DMSDB*"
                        ]
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: True
            Queue: !GetAtt QuiterFormatAppointmentQueue.Arn

  QuiterFormatAppointmentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/quiter-${Environment}-QuiterFormatInsertFilesAppointment"

  # QuiterFormatAppointmentEventMapping:
  #   Type: AWS::Lambda::EventSourceMapping
  #   Properties:
  #     BatchSize: 1
  #     EventSourceArn: !GetAtt QuiterFormatAppointmentQueue.Arn
  #     MaximumBatchingWindowInSeconds: 0
  #     FunctionName: !GetAtt QuiterFormatInsertFilesAppointment.Arn

  QuiterFormatAppointmentQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "quiter-${Environment}-QuiterFormatAppointmentQueue"
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt QuiterFormatAppointmentDeadLetterQueue.Arn
        maxReceiveCount: 3

  QuiterFormatAppointmentDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "quiter-${Environment}-QuiterFormatAppointmentDLQ"
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 10

  # QuiterFormatAppointmentDLQAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmName: !Sub "quiter-${Environment}-QuiterFormatAppointmentDLQ"
  #     AlarmDescription: There are over 1 unprocessed messages in the Quiter Format Appointment DLQ
  #     ActionsEnabled: true
  #     AlarmActions:
  #       - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering
  #     Dimensions:
  #       - Name: QueueName
  #         Value: !GetAtt QuiterFormatAppointmentDeadLetterQueue.QueueName
  #     EvaluationPeriods: 1
  #     MetricName: ApproximateNumberOfMessagesVisible
  #     Namespace: AWS/SQS
  #     Period: 300
  #     Statistic: Sum
  #     ComparisonOperator: GreaterThanThreshold
  #     Threshold: 1
  #     TreatMissingData: notBreaching

  # QuiterFormatAppointmentQueuePolicy:
  #   Type: "AWS::SQS::QueuePolicy"
  #   Properties:
  #     Queues:
  #       - !Ref QuiterFormatAppointmentQueue
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: events.amazonaws.com
  #           Action: sqs:SendMessage
  #           Resource: !GetAtt QuiterFormatAppointmentQueue.Arn
            # Condition:
            #   ArnEquals:
            #     aws:SourceArn: !GetAtt QuiterFormatAppointmentEventBridgeRule.Arn

  # QuiterFormatAppointmentEventBridgeRule:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     EventPattern:
  #       source:
  #         - "aws.s3"
  #       detail-type:
  #         - "Object Created"
  #       detail:
  #         bucket:
  #           name:
  #             - !If [ IsProd,
  #                   !Sub "arn:aws:s3:::integrations-${AWS::Region}-prod/*",
  #                   !Sub "arn:aws:s3:::integrations-${AWS::Region}-test/*"
  #                 ]
  #         object:
  #           key:
  #             - { "prefix": "raw/quiter/" }
  #     Targets:
  #       - Id: "QuiterFormatAppointmentTarget"
  #         Arn: !GetAtt QuiterFormatAppointmentQueue.Arn