AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DMS Reporting

Parameters:
  Environment:
    Description: The name of the runtime environment
    Type: String
    AllowedPattern: '^[a-zA-z0-9-]+$'
    ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens
  CEAlertTopicArn:
    Description: The ARN of the SNS topic serving as the Alert Topic for CE
    Type: String
    AllowedPattern: '^arn:aws:sns:[a-z]{2}-[a-z]+-\d{1}:\d{12}:.*$'
    ConstraintDescription: Must be an SNS ARN

Conditions:
  IsProd:
    Fn::Equals:
    - Ref: AWS::AccountId
    - 196800776222
  IsUsEast1: !Equals [ !Ref 'AWS::Region', 'us-east-1' ]

Mappings:
  VpcId:
    us-east-1:
      '196800776222': vpc-03417e688cee5bc07
      '143813444726': vpc-0b28df8980a1905d5
  Subnets:
    us-east-1:
      '196800776222':
        - subnet-0d29a385efe83bf1c
        - subnet-0e88ecdd743701e96
        - subnet-00291e028e21cb78f
        - subnet-0b1555d5fa3c8ba8e
      '143813444726':
        - subnet-030d57e39ec0df603
        - subnet-01044d580678ea63c
        - subnet-0b29db0aeb6cdabec
        - subnet-0e28d592f2ca28fb7
  SslCertificates:
    us-east-1:
      '143813444726': 'arn:aws:acm:us-east-1:143813444726:certificate/9f026b43-c690-4434-93e1-9be4ef91f67d'
      '196800776222': 'arn:aws:acm:us-east-1:196800776222:certificate/4bad36e0-d971-41e6-a2d8-a897013012be'

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Sub '${AWS::AccountId}'
        ENVIRONMENT: !Ref Environment
        CEAlertTopicArn: !Ref CEAlertTopicArn
        IS_PROD: !If [ IsProd, 1, 0 ]
        LOGLEVEL: INFO
    VpcConfig:
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetIds: !FindInMap [ Subnets, !Ref 'AWS::Region', !Ref 'AWS::AccountId' ]

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Policies:
        - PolicyName: MyLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:*Object
                Resource:
                  - !If [ IsProd,
                      !Sub "arn:aws:s3:::integrations-${AWS::Region}-prod/*",
                      !Sub "arn:aws:s3:::integrations-${AWS::Region}-test/*"
                    ]
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !If [ IsProd,
                        !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/RDS/DMS*",
                        !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/RDS/DMS*"
                      ]
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref DMSReportingSnsTopic

  DMSDailyAlert:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Timeout: 30
      Handler: dms_daily_alert.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DMS_REPORTING_SNS_TOPIC: !Ref DMSReportingSnsTopic

  S3DailyAlert:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      CodeUri: app/
      Handler: daily_s3_alert.lambda_handler

  DMSDailyAlertDeadletterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 10

  S3DailyAlertDeadletterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 10

  DMSDailyAlertScheduledEvent:
    Type: AWS::Events::Rule
    Properties:
      State: !If [ IsProd, ENABLED, DISABLED ]
      ScheduleExpression: rate(1 day)
      Description: Runs DMS Daily alerting everyday
      Targets:
        - Id: DMSDailyAlertFunctionTarget
          Arn: !GetAtt DMSDailyAlert.Arn
          DeadLetterConfig:
            Arn: !GetAtt DMSDailyAlertDeadletterQueue.Arn

  DMSDailyAlertFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DMSDailyAlert.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DMSDailyAlertScheduledEvent.Arn

  S3DailyAlertFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt S3DailyAlert.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3DailyAlertScheduledEvent.Arn

  S3DailyAlertScheduledEvent:
    Type: AWS::Events::Rule
    Properties:
      State: !If [ IsProd, ENABLED, DISABLED ]
      ScheduleExpression: rate(1 day)
      Description: Runs the S3 Daily alerting everyday
      Targets:
        - Id: S3DailyAlertFunctionTarget
          Arn: !GetAtt S3DailyAlert.Arn
          DeadLetterConfig:
            Arn: !GetAtt S3DailyAlertDeadletterQueue.Arn

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    Properties:
      GroupDescription: Permit traffic from the dms reporting
      VpcId: !FindInMap [ VpcId, !Ref 'AWS::Region', !Ref 'AWS::AccountId']
      SecurityGroupEgress:
        - Description: AllowAll
          CidrIp: 0.0.0.0/0
          IpProtocol: '-1'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Product
          Value: dms-alerting

  DMSReportingSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub dms-reporting-topic-${Environment}

  SupportSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !If [IsProd, 'support@impel.io', 'elena@impel.io']
      Protocol: email
      TopicArn: !Ref DMSReportingSnsTopic

  SupportAISnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !If [IsProd, 'aisupport@impel.io', 'elena@impel.io']
      Protocol: email
      TopicArn: !Ref DMSReportingSnsTopic
