AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AutoStock inventory integration

Parameters:
  Environment:
    Description: The name of the runtime environment
    Type: String
    AllowedPattern: '^[a-zA-z0-9-]+$'
    ConstraintDescription: Must contain only lowercase, uppercase, numbers, or hyphens

Conditions:
  IsProd:
    Fn::Equals:
    - Ref: AWS::AccountId
    - 196800776222
  IsUsEast1: !Equals [ !Ref 'AWS::Region', 'us-east-1' ]


Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Sub '${AWS::AccountId}'
        ENVIRONMENT: !Ref Environment
        REGION: !Sub '${AWS::Region}'
        IS_PROD: !If [ IsProd, 1, 0 ]
        LOGLEVEL: INFO
        SFTP_SECRET_KEY: AUTOSTOCK_SFTP
        INVENTORY_BUCKET: !Sub "inventory-integrations-${AWS::Region}-${Environment}"
        INVENTORY_INTERNAL_API_URL: !If [
          IsProd,
          !Sub "https://2oeudyys52.execute-api.us-east-1.amazonaws.com/prod",
          !Sub "https://e1r6z92cq7.execute-api.us-east-1.amazonaws.com/test"
        ]

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: S3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - !If [
                      IsProd,
                      !Sub "arn:aws:s3:::inventory-integrations-${AWS::Region}-${Environment}*",
                      !Sub "arn:aws:s3:::inventory-integrations-${AWS::Region}-${Environment}*"
                    ]
        - PolicyName: SQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sqs:SendMessage"
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource:
                  - !GetAtt FormatINVInsertQueue.Arn
                  - !GetAtt FormatINVInsertDeadLetterQueue.Arn
                  - !GetAtt DownloadSFTPFilesQueue.Arn
        - PolicyName: SecretsManagerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowGetDBInfo
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/RDS/SHARED*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/RDS/SHARED*"
                    ]
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/inventory-integrations-sftp*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/inventory-integrations-sftp*",
                    ]
                  - !If [
                      IsProd,
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/InventoryInternalApi*",
                      !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/InventoryInternalApi*",
                    ]
        - PolicyName: SNSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource:
                - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'

  InvokeSFTPFiles:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub autostock-inv-${Environment}-InvokeSFTPFiles
      CodeUri: app/
      Handler: invoke_sftp.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          DOWNLOAD_QUEUE_URL: !GetAtt DownloadSFTPFilesQueue.QueueUrl

  InvokeSFTPFilesScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Invoke SFTP AutoStock every 4 hour"
      ScheduleExpression: "cron(0 */4 * * ? *)"
      State: !If [IsProd, "ENABLED", "DISABLED"]
      Targets:
        - Arn: !GetAtt InvokeSFTPFiles.Arn
          Id: "invoke_sftp_autostock_scheduled"

  InvokeSFTPFilesScheduleLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt InvokeSFTPFiles.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt InvokeSFTPFilesScheduleRule.Arn

  InvokeSFTPFilesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/autostock-inv-${Environment}-InvokeSFTPFiles'

  InvokeSFTPFilesErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub autostock-inv-${Environment}-InvokeSFTPFiles
      AlarmDescription: AutoStock SFTP Invoke failed to execute
      ActionsEnabled: true
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref InvokeSFTPFiles
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  DownloadSFTPFiles:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub autostock-inv-${Environment}-DownloadSFTPFiles
      CodeUri: app/
      Handler: download_sftp.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      MemorySize: 1024

  DownloadSFTPFilesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/autostock-inv-${Environment}-DownloadSFTPFiles'

  DownloadSFTPFilesErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub autostock-inv-${Environment}-DownloadSFTPFiles
      AlarmDescription: AutoStock SFTP Download failed to download and process files
      ActionsEnabled: true
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DownloadSFTPFiles
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  DownloadSFTPFilesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'autostock-inv-${Environment}-DownloadSFTPFilesDLQ'
      VisibilityTimeout: 10
      MessageRetentionPeriod: 1209600

  DownloadSFTPFilesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'autostock-inv-${Environment}-DownloadSFTPQueue'
      VisibilityTimeout: 60
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DownloadSFTPFilesDeadLetterQueue.Arn
        maxReceiveCount: 3

  DownloadSFTPFilesDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'autostock-inv-${Environment}-DownloadSFTPFilesDLQ'
      AlarmDescription: There are over 1 unprocessed messages in the AutoStock SFTP Download DLQ
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DownloadSFTPFilesDeadLetterQueue.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      TreatMissingData: notBreaching

  DownloadSFTPFilesEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt DownloadSFTPFilesQueue.Arn
      MaximumBatchingWindowInSeconds: 0
      FunctionName: !GetAtt DownloadSFTPFiles.Arn

  FormatINVInsertQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'autostock-inv-${Environment}-FormatINVInsertQueue'
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 60
      RedrivePolicy:
          deadLetterTargetArn: !GetAtt FormatINVInsertDeadLetterQueue.Arn
          maxReceiveCount: 5

  FormatINVInsertDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'autostock-inv-${Environment}-FormatINVInsertDLQ'
      VisibilityTimeout: 10
      MessageRetentionPeriod: 1209600

  FormatINVInsertDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    Properties:
      AlarmName: !Sub autostock-inv-${Environment}-FormatINVInsertDLQ
      AlarmDescription: There are messages in the AutoStock FormatINVInsertDLQ Alarm
      ActionsEnabled: true
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alert_client_engineering"
      Dimensions:
        - Name: QueueName
          Value: !GetAtt FormatINVInsertDeadLetterQueue.QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      TreatMissingData: notBreaching

  FormatINVTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:inventory-integrations-sns-s3-topic-${AWS::Region}-${Environment}"
      Endpoint: !GetAtt FormatINVInsertQueue.Arn
      FilterPolicyScope: MessageBody
      FilterPolicy:
        '{"Records":{"s3":{"object":{"key":[{"prefix":"raw/autostock"}]}},"eventName":[{"prefix":"ObjectCreated:"}]}}'

  FormatINVInsertQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FormatINVInsertQueue
      PolicyDocument:
          Version: '2012-10-17'
          Id: FormatINVInsertQueuePolicy
          Statement:
            - Sid: Allow-SNS-SendMessage
              Action:
                - sqs:SendMessage
              Effect: Allow
              Resource: !GetAtt FormatINVInsertQueue.Arn
              Principal:
                  Service: sns.amazonaws.com
              Condition:
                  ArnEquals:
                      aws:SourceArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:inventory-integrations-sns-s3-topic-${AWS::Region}-${Environment}"

  FormatINVInsert:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "autostock-inv-${Environment}-FormatINVInsert"
      Description: Transform and upload unified autostock file to S3.
      Handler: format.lambda_handler
      CodeUri: app/
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      MemorySize: 1024

  FormatINVInsertLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/autostock-inv-${Environment}-FormatINVInsert'

  FormatINVInsertEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt FormatINVInsertQueue.Arn
      MaximumBatchingWindowInSeconds: 0
      FunctionName: !GetAtt FormatINVInsert.Arn
