name: Generate Coverage Report

on:
  workflow_dispatch:
  schedule:
    # Runs every hour 
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pytest
        pip install coverage
        pip install moto
        pip install aws-lambda-powertools
        pip install boto3 
        pip install pytest-mock
    - name: Run Python script
      run: python generate_coverage_report.py

    - name: Setup AWS Config
      run: |
        mkdir -p ~/.aws
        printf "[default]\naws_access_key_id = %s\naws_secret_access_key = %s\n" \
               "${{ secrets.AWS_ACCESS_KEY_ID }}" \
               "${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
        printf "[default]\nregion = %s\nsource_profile = default\noutput = json\nrole_arn=%s\n" \
             "${{ secrets.AWS_REGION }}" \
             "${{ secrets.ROLE_ARN }}" > ~/.aws/config

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage_report   
        path: coverage_report.txt