name: Enrich PR with Jira Info (Inline Script)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add_jira_details:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Grant permission to update PRs
      contents: read       # Needed for the context, though not strictly for this script without checkout

    steps:
      - name: Extract Custom Jira Ticket ID
        id: extract_jira_id # Give this step an ID to reference its outputs
        uses: actions/github-script@v7 # Use a recent version of github-script
        with:
          script: |
            // Inline JavaScript for extracting Jira ID
            /**
             * Extracts a Jira ticket ID (e.g., "scrum-123") from a string.
             * Looks for the pattern "scrum- followed by 3 to 5 digits" (adjust regex as needed).
             * @param {string} text The string to search within.
             * @returns {string | null} The found Jira ID or null if not found.
             */
            function extractJiraId(text) {
                if (!text) {
                    return null;
                }
                // Regex: 'scrum-' followed by 3 to 5 digits (e.g., 123, 12345)
                // You can adjust the {3,5} part to match your exact digit count requirements.
                const regex = /(scrum-\d{1,5})/i; // /i for case-insensitive matching
                const match = text.match(regex);
                return match ? match[1].toUpperCase() : null; // Return in uppercase to standardize
            }

            let jiraTicketId = null;

            // 1. Check Branch Name
            const branchName = context.payload.pull_request.head.ref;
            console.log(`Checking branch name: ${branchName}`);
            jiraTicketId = extractJiraId(branchName);
            if (jiraTicketId) {
                console.log(`Found Jira ID in branch name: ${jiraTicketId}`);
            }

            // 2. Check PR Title (if not found in branch name)
            if (!jiraTicketId) {
                const prTitle = context.payload.pull_request.title;
                console.log(`Checking PR title: ${prTitle}`);
                jiraTicketId = extractJiraId(prTitle);
                if (jiraTicketId) {
                    console.log(`Found Jira ID in PR title: ${jiraTicketId}`);
                }
            }

            // 3. Check PR Description (if not found in title or branch name)
            if (!jiraTicketId) {
                const prBody = context.payload.pull_request.body;
                console.log(`Checking PR description: ${prBody}`);
                jiraTicketId = extractJiraId(prBody);
                if (jiraTicketId) {
                    console.log(`Found Jira ID in PR description: ${jiraTicketId}`);
                }
            }

            // Set the output for the GitHub Action step
            if (jiraTicketId) {
                console.log(`Extracted Jira Ticket ID: ${jiraTicketId}`);
                core.setOutput('jira_ticket_id', jiraTicketId);
            } else {
                console.log('No Jira ticket ID found in branch name, PR title, or PR description.');
                core.setOutput('jira_ticket_id', ''); // Explicitly set empty if not found
            }

      - name: Get Jira Issue Details and Update PR
        # Only run this step if a Jira ticket ID was successfully extracted
        if: steps.extract_jira_id.outputs.jira_ticket_id != ''
        uses: actions/github-script@v7
        with:
          script: |
            const jiraTicketId = "${{ steps.extract_jira_id.outputs.jira_ticket_id }}";
            const jiraBaseUrl = process.env.JIRA_BASE_URL;
            const jiraUsername = process.env.JIRA_USERNAME;
            const jiraApiToken = process.env.JIRA_API_TOKEN;

            const auth = Buffer.from(`${jiraUsername}:${jiraApiToken}`).toString('base64');

            try {
              const response = await fetch(`${jiraBaseUrl}/rest/api/3/issue/${jiraTicketId}`, {
                headers: {
                  'Authorization': `Basic ${auth}`,
                  'Accept': 'application/json'
                }
              });

              if (!response.ok) {
                console.error(`Failed to fetch Jira issue: ${response.status} ${response.statusText}`);
                // Throw an error to fail the step if Jira issue cannot be fetched
                throw new Error(`Jira API error: ${response.statusText}`);
              }

              const issue = await response.json();
              const issueSummary = issue.fields.summary;
              const issueLink = `${jiraBaseUrl}/browse/${jiraTicketId}`;

              const prNumber = context.payload.pull_request.number;
              const repoOwner = context.repo.owner;
              const repoName = context.repo.repo;

              // Get current PR details
              const { data: pullRequest } = await github.rest.pulls.get({
                owner: repoOwner,
                repo: repoName,
                pull_number: prNumber,
              });

              let newPrBody = pullRequest.body || '';
              let newPrTitle = pullRequest.title;

              // Add Jira link to PR body if not already present
              // Check for both the ticket ID and the full link to avoid duplicates
              if (!newPrBody.includes(jiraTicketId) && !newPrBody.includes(issueLink)) {
                newPrBody += `\n\n---\nJira Issue: [${jiraTicketId} | ${issueSummary}](${issueLink})`;
              }

              // Prefix PR title with Jira ID if not already present
              // Use a regex to check if it's already prefixed, allowing for variations
              const jiraIdCheckRegex = new RegExp(jiraTicketId, 'i'); // Create regex to check for ID anywhere, case-insensitive
              if (!jiraIdCheckRegex.test(newPrTitle)) { // If Jira ID is NOT found in the title
                newPrTitle = `${jiraTicketId} | ${newPrTitle}`; // Then prefix it
              }

              await github.rest.pulls.update({
                owner: repoOwner,
                repo: repoName,
                pull_number: prNumber,
                title: newPrTitle,
                body: newPrBody
              });

              console.log(`Updated PR with Jira info for ${jiraTicketId}`);

            } catch (error) {
              console.error(`Error processing Jira information: ${error.message}`);
              throw error; // Fail the step if an error occurs
            }
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
