name: Linting
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'master'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Or a sufficient number like 2, 5, etc.
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Find Changed Files
      uses: ./.github/actions/find_changed_files/
      id: find-changed-files

    - name: Run Ruff on changed python files
      run: |
        for file in ${{ steps.find-changed-files.outputs.changed_files }}; do 
          if [[ "$file" == *.py ]]; then
            echo "Running ruff on $file"
            ruff check $file
          fi
        done
  
  cloudformation-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Or a sufficient number like 2, 5, etc.
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        pip install cfn-lint

    - name: Find Changed Files
      uses: ./.github/actions/find_changed_files/
      id: find-changed-files

    - name: Run cfn-lint on changed cloudformation files
      run: |
        for file in ${{ steps.find-changed-files.outputs.changed_files }}; do 
          echo "Running cfn-lint on $file"
          cfn-lint $file  
        done  