name: Linting
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'master'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Or a sufficient number like 2, 5, etc.
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Find Changed Files
      uses: ./.github/actions/find_changed_files/
      id: find-changed-files

    - name: Run Ruff on changed python files
      run: |
        for file in ${{ steps.find-changed-files.outputs.changed_files }}; do 
          if [[ "$file" == *.py ]]; then
            echo "Running ruff on $file"
            ruff check $file
          fi
        done
  
  cloudformation-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Or a sufficient number like 2, 5, etc.
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        pip install cfn-lint

    - name: Find Changed Files
      uses: ./.github/actions/find_changed_files/
      id: find-changed-files

    - name: Run cfn-lint on changed cloudformation files
      run: |
        CHANGED_SERVICES=""
        for file in ${{ steps.find-changed-files.outputs.changed_files }}; do 
          DIR_NAME=$(dirname $file)
          while [ "$DIR_NAME" != "." ]; do
            if [ -f "$DIR_NAME/template.yaml" ]; then
              echo "Found template.yaml in $DIR_NAME"
              # check if the service is in the list of changed services, if not then add it
              if [[ ! "$CHANGED_SERVICES" == *"$DIR_NAME"* ]]; then
                CHANGED_SERVICES="$CHANGED_SERVICES $DIR_NAME"
              fi
              break
            fi
            DIR_NAME=$(dirname $DIR_NAME)
          done 
        done
        echo "CHANGED_SERVICES: $CHANGED_SERVICES"