name: linters_python

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.py'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Check out the entire branch history so that diffs diff against all branch-modified files.
      - name: lint-and-annotate
        uses: swipetospin/ghactions/linters@master
        with:
          linter: flake8
        env:
          GITHUB_TOKEN: ${{ github.token }}
