name: Generate PR Summary

on:
  pull_request:
    types: [opened, reopened, synchronize] # Change this to only trigger on opened PRs in production

jobs:
  generate-pr-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests
          pip install google-genai
    
      - name: Get Jira ticket number
        id: get-jira-ticket-number
        run: |
          import os
          import re
          
          # Get branch name from GitHub context
          branch_name = os.environ.get('GITHUB_HEAD_REF', '')  # For PRs
          if not branch_name:
              branch_name = os.environ.get('GITHUB_REF_NAME', '')  # Fallback for pushes
          
          print(f"Branch name: {branch_name}")
          
          # Look for Jira ticket in branch name
          regex = r"(scrum-\d{1,5})"
          match = re.search(regex, branch_name, re.IGNORECASE)
          
          if match:
              jira_ticket = match.group(1)
              print(f"Found Jira ticket: {jira_ticket}")
              # Set output for next steps
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write(f"jira_ticket={jira_ticket}\n")
          else:
              print("No Jira ticket found in branch name")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write("jira_ticket=\n")
        shell: python