name: Ruff
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install darker
    - name: Analysing the code with ruff
      run: |
        echo $(git diff --name-only --cached -- '*.py')
        ruff check $(git diff --name-only --cached -- '*.py')
