name: CI Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize] # Trigger on new PRs, reopened PRs, or new commits to an open PR

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for testing context

      - name: Hello world
        run: |
          echo "Hello world"

      - name: Identify Changed Files
        id: identify-changed-files
        run: |
          changed_files=$(git diff --name-only -r HEAD^1 HEAD)
          echo "changed_files: $changed_files"
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

      - name: Identify changed services
        id: identify-changed-services
        run: |
          CHANGED_SERVICES=""
          for file in ${{ steps.identify-changed-files.outputs.changed_files }}; do
            DIR_NAME=$(dirname $file)
            while [ "$DIR_NAME" != "." ]; do
              if [ -f "$DIR_NAME/template.yaml" ]; then
                if [[ ! "$CHANGED_SERVICES" == *"$DIR_NAME"* ]]; then
                  echo "Adding $DIR_NAME to changed services"
                  CHANGED_SERVICES="$DIR_NAME $CHANGED_SERVICES"
                fi
                 break
              fi
              DIR_NAME=$(dirname $DIR_NAME)
            done
          done
          echo "CHANGED_SERVICES: $CHANGED_SERVICES"
          echo "changed_services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Use a recent Python version

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Setup AWS Config
        run: |
          mkdir -p ~/.aws
          printf "[default]\naws_access_key_id = %s\naws_secret_access_key = %s\n" \
                 "test-access-key-id" \
                 "test-secret-access-key" > ~/.aws/credentials
          printf "[default]\nregion = %s\nsource_profile = default\noutput = json\nrole_arn=%s\n" \
               "us-east-1" \
               "test-role-arn" > ~/.aws/config

      - name: Create coverage report directory
        run: |
          mkdir -p .reports

      - name: Run Pytest on all changed services
        run: |
          changed_services="${{ steps.identify-changed-services.outputs.changed_services }}"
          echo "Changed services: $changed_services"

          if [ -z "$changed_services" ]; then
            echo "No services changed. Skipping unit tests."
            exit 0
          fi

          COMMON_DEPS="pytest moto coverage boto3 pytest-mock"

          for service_path in $changed_services; do
            echo "--- Running tests for service: $service_path ---"
            service_name="${service_path//\//-}"
            VENV_DIR=".venv-$service_name"

            rm -rf "$VENV_DIR"
            python3 -m venv "$VENV_DIR"
            source "$VENV_DIR/bin/activate"

            pip install $COMMON_DEPS
            SERVICE_REQUIREMENTS_FILE="${service_path}/app/requirements.txt"
            if [ -f "$SERVICE_REQUIREMENTS_FILE" ]; then
              echo "Installing service-specific dependencies from $SERVICE_REQUIREMENTS_FILE..."
              pip install -r "$SERVICE_REQUIREMENTS_FILE"
            else
              echo "No service-specific requirements.txt found at $SERVICE_REQUIREMENTS_FILE. Using only common dependencies."
            fi

            coverage run -m pytest $service_path/tests || true
            coverage xml -o .reports/coverage-${service_name}.xml || true

            deactivate
            echo "--- Finished tests for service: $service_path ---"
          done
        shell: bash # Explicitly use bash for this step

      - name: Run flake8 on all changed files
        continue-on-error: true
        run: |
          pip install flake8

          changed_files="${{ steps.identify-changed-files.outputs.changed_files }}"
          echo "Changed files: $changed_files"

          PY_FILES=$(echo "$changed_files" | tr ' ' '\n' | grep '\.py$') || true
          PY_FILES=$(echo "$PY_FILES" | tr '\n' ' ')
          PY_FILES="${PY_FILES## }"
          echo "Changed .py files: $PY_FILES"

          if [ -z "$PY_FILES" ]; then
            echo "No changed .py files. Skipping ruff."
            exit 0
          fi

          echo "flake8 $PY_FILES"
          flake8 $PY_FILES || true
          echo "flake8 --format=pylint --output-file=.reports/flake8-report.txt $PY_FILES"
          flake8 --format=pylint --output-file=.reports/flake8-report.txt $PY_FILES
                
      - name: Run cfn-lint on all changed files
        continue-on-error: true
        run: |
          pip install cfn-lint

          changed_files="${{ steps.identify-changed-files.outputs.changed_files }}"
          echo "Changed files: $changed_files"

          TEMPLATE_FILES=$(echo "$changed_files" | tr ' ' '\n' | grep 'template\.yaml$') || true
          TEMPLATE_FILES=$(echo "$TEMPLATE_FILES" | tr '\n' ' ')
          TEMPLATE_FILES="${TEMPLATE_FILES## }"
          echo "Changed template files: $TEMPLATE_FILES"

          if [ -z "$TEMPLATE_FILES" ]; then
            echo "No changed template files. Skipping cfn-lint."
            exit 0
          fi

          echo "cfn-lint $TEMPLATE_FILES"
          cfn-lint $TEMPLATE_FILES || true
          echo "cfn-lint --format json $TEMPLATE_FILES"
          cfn-lint --format json $TEMPLATE_FILES > .reports/cfn-lint-report.json
         
      - name: Display report files
        run: |
          ls -al .reports

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate Check
        id: sonar-quality-gate-check
        uses: SonarSource/sonarqube-quality-gate-action@master
        with: 
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

