name: CloudFormation Lint New

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history for changed file detection
          fetch-depth: 0
      
      - name: Install cfn-lint
        run: |
          pip install cfn-lint
      
      - name: Modified files
        id: changed-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          fi

      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do  
            echo "$file was changed"
          done
    

    