name: SAM YAML Linter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch full history to accurately determine changed files for git diff
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Use a recent Python version compatible with SAM CLI

    - name: Install AWS SAM CLI
      run: |
        python -m pip install --upgrade pip
        pip install aws-sam-cli

    - name: Find and lint changed YAML files
      id: lint-yaml
      run: |
        echo "--- Starting SAM YAML Linting ---"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_SHA: ${{ github.sha }}"

        # Determine the base commit for comparison
        # For a push, github.event.before is the previous commit SHA.
        # If it's the very first commit or a new branch push, github.event.before will be all zeros.
        if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
          echo "First commit or new branch push detected."
          # If first commit/new branch, compare against an empty tree to get all files,
          # or simply find all YAML files. Let's find all existing YAML files.
          CHANGED_YAML_FILES=$(find . -type f -name "*.yaml" -o -name "*.yml" | sort)
          echo "No previous commit for diff. Linting all existing YAML files."
        else
          BASE_COMMIT="${{ github.event.before }}"
          CURRENT_COMMIT="${{ github.sha }}"
          echo "Comparing changes between $BASE_COMMIT and $CURRENT_COMMIT"

          # Get names of changed YAML files between the two commits
          # --diff-filter=AMCR picks Added, Modified, Copied, Renamed files
          # Only consider .yaml and .yml extensions
          CHANGED_YAML_FILES=$(git diff --name-only --diff-filter=AMCR "$BASE_COMMIT" "$CURRENT_COMMIT" -- '*.yaml' '*.yml' | sort)
          echo "Changed YAML files identified by git diff:"
        fi

        # Check if any YAML files were found
        if [ -z "$CHANGED_YAML_FILES" ]; then
          echo "No YAML files changed in this push. Skipping linting."
          exit 0 # Exit successfully if no files to lint
        else
          echo "$CHANGED_YAML_FILES" # Echo the list of files
          echo "" # Add a blank line for readability
        fi

        HAS_LINTING_ERRORS=false

        # Loop through each changed YAML file and run sam validate --lint
        while IFS= read -r file; do
          if [ -f "$file" ]; then # Ensure the file exists (might be deleted in diff)
            echo "--- Linting: $file ---"
            if ! sam validate --lint --template "$file"; then
              echo "!!! Linting failed for $file !!!"
              HAS_LINTING_ERRORS=true
            else
              echo "--- Linting successful for $file ---"
            fi
            echo "" # Add a blank line for readability
          fi
        done <<< "$CHANGED_YAML_FILES"

        if [ "$HAS_LINTING_ERRORS" = true ]; then
          echo "!!! One or more YAML files failed linting. Please review the output above. !!!"
          exit 1 # Fail the job if any linting errors occurred
        else
          echo "--- All changed YAML files passed SAM linting. ---"
        fi
